"""Update database schema

Revision ID: 9a1f52f451e9
Revises: f6005981f41d
Create Date: 2025-03-13 20:25:46.400636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1f52f451e9'
down_revision: Union[str, None] = 'f6005981f41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('missed_contributions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'missed_contributions')
    # ### end Alembic commands ###
